---
title: Errore del compilatore CS0103
ms.date: 07/20/2015
f1_keywords:
- CS0103
helpviewer_keywords:
- CS0103
ms.assetid: fd1f2104-a945-4dba-8137-8ef869826062
ms.openlocfilehash: cea257533266abdfced974c1ca560050a194e44b
ms.sourcegitcommit: 8b8dd14dde727026fd0b6ead1ec1df2e9d747a48
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 09/27/2019
ms.locfileid: "71332061"
---
# <a name="compiler-error-cs0103"></a>Errore del compilatore CS0103

Il nome "identifier" non esiste nel contesto corrente

 Si è tentato di usare un nome che non esiste nella classe, nello [spazio dei nomi](../keywords/namespace.md) o nell'ambito. Controllare l'ortografia del nome, le direttive using e i riferimenti all'assembly per verificare la disponibilità del nome che si tenta di utilizzare.

 Questo errore si verifica di frequente se si dichiara una variabile in un ciclo o un blocco `try` o `if`, quindi si tenta di accedervi da un blocco di codice di inclusione o da un blocco di codice separato, come illustrato nell'esempio seguente:

```csharp
using System;

class MyClass1
{
    public static void Main()
    {
        try
        {
            // The following declaration is only available inside the try block.
            var conn = new MyClass1();
        }
        catch (Exception e)
        {  
            // The following expression causes error CS0103, because variable
            // conn only exists in the try block.
            if (conn != null)
                Console.WriteLine("{0}", e);
        }
    }
}
```

 Nell'esempio seguente viene risolto l'errore:

```csharp
using System;

class MyClass2
{
    public static void Main()
    {
        // To resolve the error in the example, the first step is to
        // move the declaration of conn out of the try block. The following
        // declaration is available throughout the Main method.
        MyClass2 conn = null;
        try
        {
            // Inside the try block, use the conn variable that you declared
            // previously.
            conn = new MyClass2();
        }
        catch (Exception e)
        {
            // The following expression no longer causes an error, because
            // the declaration of conn is in scope.
            if (conn != null)
                Console.WriteLine("{0}", e);
        }
    }
}
```
